#!/usr/bin/env Rscript

# ============================================================
# R script to run BayesPrism on all per-donor references
# generated by prepare_perdonor_reference.py
#
# Usage:
#   Rscript BayesPrism_perDonor.R <DATASET_NAME>
# ============================================================

options(repos = c(CRAN = "https://cloud.r-project.org"))

# load/install packages
pkgs <- c("scran", "SingleCellExperiment", "BayesPrism", "InstaPrism")
for (p in pkgs) {
  if (!requireNamespace(p, quietly = TRUE)) {
    stop(p, " is not installed. Please install it first.")
  }
}
library(scran)
library(SingleCellExperiment)
library(BayesPrism)
library(InstaPrism)

args <- commandArgs(trailingOnly = TRUE)
if (length(args) == 0) stop("Please supply a dataset name, e.g. Real_ADP")
data_type <- args[1]

# --- Set up directories ---
script_dir <- getwd() # or another logic to detect your script location
bulks_path <- import_path <- file.path(script_dir, "..", "data", "deconvolution", data_type)
import_path <- file.path(script_dir, "..", "data", "deconvolution", data_type)
export_path <- file.path(script_dir, "..", "results", data_type)
cat("Import path:", import_path, "\n")
cat("Export path:", export_path, "\n")

if (!dir.exists(export_path)) dir.create(export_path, recursive = TRUE)

transformations <- c(
  "rawSN",
  "pcaSN",
  "degSN",
  "degOtherSN",
  "degIntSN",
  "degRandSN",
  "degPCA_SN",
  "scviSN",
  "scvi_LSshift_SN",
  "degScviSN",
  "degScviLSshift_SN"
)

# 1) load bulks
bulks_file <- file.path(import_path, "processed_bulks.csv")
if (!file.exists(bulks_file)) stop("Missing ", bulks_file)
mixture_data <- as.matrix(read.csv(bulks_file, row.names = 1, check.names = FALSE))
cat("Loaded bulks:", dim(mixture_data), "\n")

# 2) per-donor transforms
# read donor list (one line, comma‐separated)
donors_csv <- file.path(import_path, "donors.csv")
if (!file.exists(donors_csv)) stop("Missing donors.csv at ", donors_csv)
line <- readLines(donors_csv, n = 1)
donors <- strsplit(line, ",", fixed = TRUE)[[1]]

for (d in donors) {
  cat("donor: ", d)

  for (trans in transformations) {
    # Build the file names
    prefix <- paste0("ref_", d, "_", trans)
    signal_file <- file.path(import_path, paste0(prefix, "_signal.csv"))
    cell_state_file <- file.path(import_path, paste0(prefix, "_cell_state.csv"))
    cat("signal_file:\n")
    cat(signal_file)
    cat("\n")
    cat("cell_state_file:\n")
    cat(cell_state_file)
    if (!file.exists(signal_file) || !file.exists(cell_state_file)) {
      cat(
        "Skipping reference for transform:", trans,
        "because files not found.\n"
      )
      next
    }

    cat("\nProcessing transform:", trans, "\n")

    # Read them
    signal_data <- read.csv(signal_file, row.names = 1, stringsAsFactors = FALSE)
    cell_state <- read.csv(cell_state_file, stringsAsFactors = FALSE)

    # Subset mixture_data to match genes
    common_genes <- intersect(rownames(mixture_data), rownames(signal_data))
    if (length(common_genes) < 500) {
      cat("Skipping transform:", trans, " - fewer than 500 overlapping genes.\n")
      next
    }

    mixture_sub <- mixture_data[common_genes, , drop = FALSE]
    signal_sub <- signal_data[common_genes, , drop = FALSE]

    # Build SingleCellExperiment
    scExpr <- SingleCellExperiment(assays = list(counts = as.matrix(signal_sub)))

    # Format the cell_state
    cell_type_labels <- t(cell_state[1])
    cell_state_labels <- t(cell_state[2])

    refPhi_obj <- refPrepare(
      sc_Expr = assay(scExpr, "counts"),
      cell.type.labels = cell_type_labels,
      cell.state.labels = cell_state_labels
    )

    # Run InstaPrism
    results <- InstaPrism(
      bulk_Expr = mixture_sub,
      refPhi_cs = refPhi_obj,
      n.iter = 5000,
      n.core = 16
    )

    # Save output
    cell_frac <- results@Post.ini.cs@theta
    out_prop <- file.path(export_path, paste0(prefix, "_BayesPrism_proportions.csv"))
    write.table(cell_frac, out_prop, sep = "\t", quote = FALSE, row.names = TRUE, col.names = NA)

    # Also save the actual reference used after any possible filtering in InstaPrism
    cell_ref <- results@initial.reference@phi.cs
    out_ref <- file.path(export_path, paste0(prefix, "_BayesPrism_usedref.csv"))
    write.table(cell_ref, out_ref, sep = "\t", quote = FALSE, row.names = TRUE, col.names = NA)

    cat("Done with transform:", trans, "\n")
  }
}

cat("All per-donor references deconvolved.\n")
